# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of money paid by the customer.', max_digits=4)),
                ('is_paid', models.BooleanField()),
            ],
            options={
                'ordering': ('customer',),
            },
        ),
        migrations.RenameField(
            model_name='service',
            old_name='car_price',
            new_name='car_wash_price',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='truck_price',
            new_name='truck_wash_price',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_revenue',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_wash_manager.Customer'),
        ),
    ]
