# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_manager', '0002_auto_20170608_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='customer',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount of money made from customer.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='times_visited',
            field=models.IntegerField(default=0, help_text='Amount of times customer has been to car wash.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount of money paid by the customer.', max_digits=8),
        ),
    ]
