# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_manager', '0003_auto_20170609_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='additional_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional cost to customer for muddy truck.', max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_muddy',
            field=models.BooleanField(default=False),
        ),
    ]
