# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash_manager', '0005_remove_transaction_is_muddy'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_charge_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional cost to customer for washing a muddy truck.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='service',
            name='car_wash_price',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Price for washing a regular car.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='service',
            name='truck_wash_price',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Price for washing a regular truck.', max_digits=4),
        ),
    ]
